# Generated by Django 5.2.8 on 2025-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified_in_app',
            field=models.BooleanField(default=False),
        ),
    ]
